### ISSUE TITLE
如何设置其高度? 默认的高度178px似乎对于pc端来说有点过矮了

### ISSUE THREAD

**Issue by SealinGp** [warriorBrian/v-json-editor#6]
试了一下css均无效
```
div.jsonEditor-vue {
  height: 300px;
}

div.jsoneditor-mode-code {
  height: 300px;
}
```

而通过console设置高度后,超过 178px高度的又被隐藏了

![image](https://user-images.githubusercontent.com/32982627/113258767-f2ee8b00-92fe-11eb-8c51-568379561bc6.png)

**Comment by SealinGp** [comment]
已解决,[答案来自这里](https://github.com/dirkliu/vue-json-editor/issues/28)
1. <style lang="scss" scoped> 中的 scoped 去掉
2. 加上css
```
div.jsonEditor-vue {
  height: 300px;
}
```

实测在code模式下的默认高度可用,并且内容也不会被滚动隐藏

![image](https://user-images.githubusercontent.com/32982627/113264915-1bc64e80-9306-11eb-9ac4-cf5a91594c88.png)

**Comment by warriorBrian** [comment]
@SealinGp 这是jsoneditor的默认行为，可以使用css来覆盖这种默认行为:

```js
// css 可以使用 /deep/ 或者 >>>
<style lang="less" scoped>
.div /deep/ .jsonEditor-vue {
  height: 750px;
}
</style>
```

```js
// less
<style lang="less" scoped>
.div {
  & /deep/ .jsonEditor-vue {
    height: 750px;
  }
}
</style>
```
