### ISSUE TITLE
v-model 未随编辑内容变化

### ISSUE THREAD

**Issue by ckwillling** [warriorBrian/v-json-editor#7]
```vue
<template>
  <div>
    <v-json-edit v-model="jsonData" edit drag @change="changeHandle"></v-json-edit>
    <!-- a-input v-model="jsonData" /-->
    <span>{{ jsonData }}</span>
  </div>
</template>
<script>
export default {
  components: {},
  data() {
    return {
      jsonData: {} // 渲染值
    }
  },
  methods: {
    changeHandle(val) {
      // 改变值
      console.log('ccccccc', val, this.jsonData)
    }
  }
}
</script>
```

Node: v10.20.1
  vue: ^2.6.10

基于 vue-antd-pro 3.0.0 版本

以上, 编辑操作时, 未报错, 但 jsonData 并没有变化...

另外, 这个编辑器和https://github.com/yansenlei/VJsoneditor 很像, 是fork 过来的吗

**Comment by warriorBrian** [comment]
@ckwillling 尝试在`changeHandle`中接收到改变值后，手动改变data中的`jsonData`。我觉得可以达到改变`jsonData`的目的。

**Comment by ckwillling** [comment]
> @ckwillling 尝试在`changeHandle`中接收到改变值后，手动改变data中的`jsonData`。我觉得可以达到改变`jsonData`的目的。

试过了, 这种操作会导致每一次鼠标操作都会将光标定位到第一行第一个位置, 不现实

**Comment by warriorBrian** [comment]
@ckwillling 光标定位第一行这个问题已经解决了，能告诉下你的版本。目前最新版是 `0.8.0`,在之前版本存在了这个问题，已经解决。

**Comment by warriorBrian** [comment]
@ckwillling 这个问题我也观察到，我的做法是在`data`中定义一个同等的变量，用来更新视图层，双向绑定值与change改变值分开，这样不会出现光标定位第一行，及可以达到你的目的。

```js
data () {    
  return {      
      json: {}, 
      changeData: {} // 这里存放改变过后的值
  }  
},
```

**Comment by warriorBrian** [comment]
@ckwillling 关于此编辑器是由`jsoneditor`基础上进行封装为vue使用版本。
